### ISSUE TITLE
vfsStream::newFile allows slashes in filenames

### ISSUE THREAD

**Issue by andzandz** [bovigo/vfsStream#142]
Hi! If you do this:

```
sStream::setup();
vfsStream::newFile('text/mytext.txt', 0755)
    ->withContent("hello world")
    ->at($vfs_root);
vfsStream::newFile('notes/mynote.txt', 0755)
    ->withContent("hello world 2")
    ->at($vfs_root);

print_r(scandir($vfs_root->url()));
```

You will see:

```
Array
(
    [0] => .
    [1] => ..
    [2] => notes/mynote.txt
    [3] => text/mytext.txt
)
```

`scandir` doesn't recursively drill down into subdirectories - in this case it should output just the directory names, `notes` and `text`, not `notes/mynote.txt`. These files were created in the root folder, with slashes in the filenames, which is not allowed in a real filesystem.

Also, `scandir($vfs_root->url() . "/notes");` will throw an error as the notes directory does not exist.

As the intention is to create directories, I suggest either throw an error or create the intended directory.

Very useful filesystem mocking library by the way! We use it in a number of our projects. Cheers for the effort.

**Comment by mikey179** [comment]
After thinking about this for some time I think throwing the exception is the better choice. However, I don't think that this change should be in a bugfix release, so I add this to the 2.0 milestone.

**Comment by kiler129** [comment]
@mikey179: Please, rethink that change - some filesystems allows creating files with slashes - notable example is HFS+ on macOS.

**Comment by andzandz** [comment]
@kiler129 What, really? If anything that encourages bad (and unportable) design. I wouldn't bother supporting it personally.
