### ISSUE TITLE
Problem with SplFileObject and vfs for line counting

### ISSUE THREAD

**Issue by dogmatic69** [bovigo/vfsStream#153]
I have been using this to test some CSV code that makes use of `SplFileObject` for counting the lines in the CSV file.

I have found that using vfs does not return the same count.

## Tests

    /**
     * 8 fails, 2 pass
     * @dataProvider countVfsDataProvider
     */
    public function testCountVfs($data, $expected)
    {
        $file = vfsStream::url('tmp/data.csv');
        file_put_contents($file, $data);

        $file = new \SplFileObject($file, 'r');
        $file->seek($file->getSize());
        $this->assertEquals($expected, $file->key());
    }

    /**
     * 10 passes
     * @dataProvider countVfsDataProvider
     */
    public function testCountVfsNative($data, $expected)
    {
        $file = '/tmp/data.csv';
        file_put_contents($file, $data);

        $file = new \SplFileObject($file, 'r');
        $file->seek($file->getSize());
        $this->assertEquals($expected, $file->key());
    }

    public function countVfsDataProvider()
    {
        return [
            'test-01' => ["header\r\n1\r\n2\r\n3\r\n", 4],
            'test-02' => ["header\n1\n2\n", 3],
            'test-03' => ["header\n1\n2", 2],
            'test-04' => ["header\n1\n,\n,\n,\n", 5],
            'test-05' => ["header\n", 1],
            'test-06' => ['', 0],
            'test-07' => ["\n", 1],
            'test-08' => ["\r\n", 1],
            'test-09' => ["\n\n", 2],
            'test-10' => ["\r\n\r\n", 2],
        ];
    }

## Test output
```
There were 8 failures:

1) VfsTest::testCountVfs with data set "test-01" ('header
1
2
3
', 4)
Failed asserting that 3 matches expected 4.

/path/to/vfs.test.php:82

2) VfsTest::testCountVfs with data set "test-02" ('header
1
2
', 3)
Failed asserting that 2 matches expected 3.

/path/to/vfs.test.php:82

3) VfsTest::testCountVfs with data set "test-04" ('header
1
,
,
,
', 5)
Failed asserting that 4 matches expected 5.

/path/to/vfs.test.php:82

4) VfsTest::testCountVfs with data set "test-05" ('header
', 1)
Failed asserting that 0 matches expected 1.

/path/to/vfs.test.php:82

5) VfsTest::testCountVfs with data set "test-07" ('
', 1)
Failed asserting that 0 matches expected 1.

/path/to/vfs.test.php:82

6) VfsTest::testCountVfs with data set "test-08" ('
', 1)
Failed asserting that 0 matches expected 1.

/path/to/vfs.test.php:82

7) VfsTest::testCountVfs with data set "test-09" ('

', 2)
Failed asserting that 1 matches expected 2.

/path/to/vfs.test.php:82

8) VfsTest::testCountVfs with data set "test-10" ('

', 2)
Failed asserting that 1 matches expected 2.

                                       
FAILURES!                              
Tests: 20, Assertions: 20, Failures: 8.
```

**Comment by mikey179** [comment]
It seems the line counting is done entirely in [`SplFileObject`](https://github.com/php/php-src/blob/c8aa6f3a9a3d2c114d0c5e0c9fdd0a465dbb54a5/ext/spl/spl_directory.c). If I change it from `$file->seek()` (which BTW expects a line number to seek to, not a byte offset) to
```
while ($file->valid()) {
    $s = $file->key() . ': ' . $file->current(); // call current() otherwise the loop will run forever
    if (!$file->eof()) $file->next();
}
```
then all test cases pass.

Looking into the calls against `vfsStreamWrapper::stream_read()` it is always called to read the default of 8192 bytes - so it's up to PHP (or SPL in this case) itself to count the lines which are within those bytes. I'm not sure if there's anything here that vfsStream could do other or better to solve this.

**Comment by dogmatic69** [comment]
`getSize` is used as an arbitrary number, some examples use `PHP_INT_MAX` but that has performance issues on larger files. `getSize` will always be smaller than `PHP_INT_MAX` but larger than the number of lines.

In terms of speed, looping through the file as you are doing is one of the slowest methods for a line count. Per [this ](https://stackoverflow.com/a/13060695/191140) it's  150k times faster to use `->seek(->getSize())` and iteration. It's also a lot less boiler plate code to use `seek`.

This is all besides the point though, the problem is that using a `vfsStream` with `SplFileObject` behaves differently to using an actual file.

In my test `test-03` and `test-06` are passing, they are the only two lines that do not end in a new line. I would suspect this has something to do with the problem.

**Comment by mikey179** [comment]
I tried to find out what vfsStream methods are called. Basically, the `SplFileObject->seek()` call reads the whole file in one go (because it is less than 8192 bytes), and vfsStream returns the complete content including the trailing line. Subsequently all checks for EOF return `true` as one would expect. I don't know why `SplFileObject` doesn't count the trailing line, but I have absolutely no idea how vfsStream should behave different here.

**Comment by jamayka** [comment]
It is SplFileObject bug: https://bugs.php.net/bug.php?id=77828

**Comment by bizurkur** [comment]
Closing since this is not an issue with vfsStream
