### ISSUE TITLE
Different behaviour for is_readable() between 1.6.5 and 2.0.0-dev

### ISSUE THREAD

**Issue by mikey179** [bovigo/vfsStream#167]
From #166, redacted:

```php
$root = vfsStream::setup('php-unit', 0777);
$root->chown(vfsStream::getCurrentUser());
$root->chgrp(vfsStream::getCurrentGroup());

$file = new vfsStreamFile('file.ext', 0400);
$file->chown(vfsStream::getCurrentUser() + 1);
$file->chgrp(vfsStream::getCurrentGroup() + 1);
$file->content('foobar');
$root->->addChild($file);

var_dump(is_readable($file->url()));
```
Using version **`1.6.5`** I get the following:
```
false
```
Using version **`2.0.x-dev`** I get the following:
```
true
```

As I don't have an explanation for this different behaviour right away this must be investigated.

**Comment by bizurkur** [comment]
Not sure what was broken at the time, but I tested this today on 2.0.x-dev and got the expected `false`. This doesn't seem to be an issue anymore.

**Comment by bizurkur** [comment]
Clarification: On *nix systems, this works as expected. On Windows, it doesn't appear to honor the group/other perms. When tested on the 1.6.5 release, it gave the same failure as 2.x on Windows. Both work fine on *nix systems.
