### ISSUE TITLE
composer 2.0 deprecation warning due to uppercase character

### ISSUE THREAD

**Issue by blkperl** [bovigo/vfsStream#173]
When running composer commands I get the following deprecation warning on composer 1.8.2.

> Deprecation warning: require-dev.mikey179/vfsStream is invalid, it should not contain uppercase characters. Please use mikey179/vfsstream instead. Make sure you fix this as Composer 2.0 will error.

**Comment by mundschenk-at** [comment]
You can simply lowercase the package name in your `composer.json` - the lookup is case-insensitive anyway. Of course it should also be changed here.

**Comment by blkperl** [comment]
A pr was opened https://github.com/mikey179/vfsStream/pull/174 for this.

**Comment by mikey179** [comment]
I just released 1.6.6 with the fix from #174.

**Comment by borekb** [comment]
What am I doing wrong?

```
$ composer remove mikey179/vfsstream
# OK

$ composer require --dev mikey179/vfsstream
Using version ^1.6 for mikey179/vfsStream
./composer.json has been updated
Deprecation warning: require-dev.mikey179/vfsStream is invalid, it should not contain uppercase characters. Please use mikey179/vfsstream instead. Make sure you fix this as Composer 2.0 will error.
```

Why is it still adding vsfStream with upper case? This is in my `composer.lock` after the above:

```json
{
    "name": "mikey179/vfsStream",
    "version": "v1.6.6",
    "source": {
        "type": "git",
        "url": "https://github.com/bovigo/vfsStream.git",
        "reference": "095238a0711c974ae5b4ebf4c4534a23f3f6c99d"
    },
    "dist": {
        "type": "zip",
        "url": "https://api.github.com/repos/bovigo/vfsStream/zipball/095238a0711c974ae5b4ebf4c4534a23f3f6c99d",
        "reference": "095238a0711c974ae5b4ebf4c4534a23f3f6c99d",
        "shasum": ""
    },
    "// etc."
}
```

**Comment by borekb** [comment]
The workaround was to update `composer.json` manually && run `composer update nothing` to update the `content-hash` field in `composer.lock`.

Still, I don't quite understand why vfsStream still installed with the upper case letter at version 1.6.6.

**Comment by allejo** [comment]
I'm not sure if this is related but searching for vfsstream on Packagist returns duplicate results with different cases. I've opened https://github.com/composer/packagist/issues/1012 to see if that's intended behavior but that might be the cause?
