### ISSUE TITLE
How to get child files names

### ISSUE THREAD

**Issue by vishalinfyom** [bovigo/vfsStream#177]
Here is my code,
 

        $root = vfsStream::setup('home');

        $file1 =  vfsStream::url('home/file1.txt');
        file_put_contents($file1 , "The new contents of the file - 1");

        $file2 =  vfsStream::url('home/file2.txt');
        file_put_contents($file2 , "The new contents of the file - 2");

Now i want to get all files exist into `home`, is it possible ?

and easiest way by i can find my files name that exist into dir `home`

**Comment by vishalinfyom** [comment]
@mikey179 any updates ?

**Comment by allejo** [comment]
Oops! My bad about closing the issue prematurely, my hand slipped.

What is it you’re trying to achieve? Your code example doesn’t seem to be creating any directories or files. Take a look at [the tutorial on the wiki](https://github.com/bovigo/vfsStream/wiki/Tutorial#creating-a-file) to see how you can create a file.

**Comment by vishalinfyom** [comment]
@allejo i hope now you are able to understand what i want 

https://github.com/bovigo/vfsStream/issues/177#issue-428201135

**Comment by allejo** [comment]
Thanks for the clarification! You can simply use [`scandir()`](https://www.php.net/manual/en/function.scandir.php).

```php
$root = vfsStream::setup('home');

$file1 =  vfsStream::url('home/file1.txt');
file_put_contents($file1 , "The new contents of the file - 1");

$file2 =  vfsStream::url('home/file2.txt');
file_put_contents($file2 , "The new contents of the file - 2");

$files = scandir($root->url());
print_r($files);
```

Or you can use any other method of iterating through a directory (courtesy of StackOverflow).

- [List all files in one directory PHP](https://stackoverflow.com/questions/15774669/list-all-files-in-one-directory-php)
- [Getting the names of all files in a directory with PHP](https://stackoverflow.com/questions/2922954/getting-the-names-of-all-files-in-a-directory-with-php)
- [PHP list all files in directory](https://stackoverflow.com/questions/3826963/php-list-all-files-in-directory)

**Comment by vishalinfyom** [comment]
Got it, thanks @allejo
