### ISSUE TITLE
PHP 7.4 error

### ISSUE THREAD

**Issue by mimmi20** [bovigo/vfsStream#198]
During a test I got this error:

```php
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in .../vendor/mikey179/vfsstream/src/main/php/org/bovigo/vfs/vfsStream.php on line 340
```

**Comment by bizurkur** [comment]
It sounds like you're using an older version. Please try updating to [version 1.6.7](https://github.com/bovigo/vfsStream/releases/tag/v1.6.7) which fixed this issue.
