### ISSUE TITLE
Workaround for the realpath() false negative

### ISSUE THREAD

**Issue by jclaveau** [bovigo/vfsStream#207]
Presently, using the native realpath() generates false negative on vfs:// urls.
One workaround is to override realpath() in the namespace of the tests so the native one is used in production (https://stackoverflow.com/questions/22365519/vfsstream-paths-and-realpath):
```php
/**
 * This function overrides the native realpath($url) function, removing
 * all the "..", ".", "///" of an url. Contrary to the native one, 
 * 
 * @param string $url
 * @param string|bool The cleaned url or false if it doesn't exist
 */
function realpath(string $url)
{
    preg_match("|^(\w+://)?(/)?(.*)$|", $url, $matches);
    $protocol = $matches[1];
    $root     = $matches[2];
    $rest     = $matches[3];
    
    $split = preg_split("|/|", $rest);

    $cleaned = [];
    foreach ($split as $item) {
        if ($item === '.' || $item === '') {
            // If it's a ./ then it's nothing (just that dir) so don't add/delete anything
        } elseif ($item === '..') {
            // Remove the last item added since .. negates it.
            $removed = array_pop($cleaned);
        } else {
            $cleaned[] = $item;
        }
    }

    $cleaned = $protocol.$root.implode('/', $cleaned);
    return file_exists($cleaned) ? $cleaned : false;
}
```

I used it with success but it probably deserves to be implemented / tested with your own API and also documented for users, which is why I open this bug btw.

**Comment by allejo** [comment]
Unless something has changed in PHP or there's a new API available for us, this is a [known issue](https://github.com/bovigo/vfsStream/wiki/Known-Issues) and not something we can implement/fix.
