### ISSUE TITLE
GitHub Actions instead Travis/AppVeyor

### ISSUE THREAD

**Issue by mikey179** [bovigo/vfsStream#215]
In the last few days I've been experimenting with using GitHub Workflows/Actions instead of Travis CI or AppVeyor over on [bovigo/assert](https://github.com/bovigo/assert) and [bovigo/callmap](https://github.com/bovigo/callmap). I think running the build that way has some advantages, but it also comes with some disadvantages. Before creating a PR for vfsStream I'd like to know what you think. You can see past runs and how they look like on the Actions tab of both projects, to see the configuration have a look at the `.github/workflows` directories.

Advantages:
- No need to run separate configurations and different providers for testing on Windows and Linux.
- Testing on macOS comes for free (not that I think it's much different from Linux, but you never know...).
- Better integration of errors into the GitHub UI as they can be annotated to PRs, commits or even exact lines in a diff. Haven't exactly tested that yet as I didn't want to introduce an error just to verify that it works. 😁 However, it also [surfaced warnings for code in a dependency](https://github.com/bovigo/callmap/actions/runs/41749453), but didn't attribute it to code in the repository itself, as the dependency is not checked into the repo of course.
- Ability to separate checks for PHPStan (and CodeSniffer which we have here in vfsStream) from the actual test run. If they fail they would appear as separate checks within a PR. I think this is good for contributors as they can better see why and where there's a problem with the PR.

Disadvantages:
- It is not possible to trigger a rerun of a specific build via the GitHub UI. With Travis, you can trigger a rerun of every build via the web UI. It bite me once because I missed adding a secret to the repository via repository settings, but I don't think it's a big deal.
- Integration with Coveralls isn't as good as with Travis CI. For Travis CI Coveralls is able to understand the different builds in a matrix and attribute them separately to the commit. Such a feature doesn't exist for GitHub Actions, so I had to restrict it to submit coverage data for one of the builds only.

If you think it's a good idea to switch I'd prepare a PR. If you just have questions feel free to ask.

**Comment by bizurkur** [comment]
👍 I've wanted to test Actions sometime soon because I love the idea of the integrated feedback in the PR, which I didn't realize they did until a couple weeks ago.

I think the advantages outweigh the disadvantages

**Comment by allejo** [comment]
> It is not possible to trigger a rerun of a specific build via the GitHub UI. With Travis, you can trigger a rerun of every build via the web UI. It bite me once because I missed adding a secret to the repository via repository settings, but I don't think it's a big deal.

If the build on GH Actions fails, then you **can** trigger a rerun. However, you can't currently rerun a successful build.

But I agree that the advantages on this outweighs the disadvantages. GH Actions aren't going anywhere so I'm sure their features will improve moving forward potentially addressing these disadvantages.

**Comment by jaapio** [comment]
You might want to have a look at the pipeline of phpdocumentor for example which we have extended a lot in the past months. it Could help you with some inspiration.

**Comment by mikey179** [comment]
I prepared everything so far in PR #219. I'll close this issue, let's have further discussions on the concrete configuration within the PR. Feel free to add comments and questions even though the PR is still in the draft phase.
