### ISSUE TITLE
Attempting to require() or include() a vfsStream file dies silently

### ISSUE THREAD

**Issue by mrtorrent** [bovigo/vfsStream#22]
Hi, I'm trying to use vfsStream to mock the target of a require/include call in a PHPUnit test, but it just dies silently. I've tried setting error reporting to E_ALL and turning on allow_url_include both at runtime and in php.ini. I've searched and found only [a PHP bug report](https://bugs.php.net/bug.php?id=50898) with a snarky developer answer and [a StackOverflow question](http://stackoverflow.com/questions/7520702/include-or-require-a-vfsstream-file) with no answer.

Any help tracking this down would be much appreciated.

**Comment by stoufa06** [comment]
@mikey179 This issue happened to me, i am using php 8.2 command line with allow_url_fopen without suhosin. it created a folder vfs: in my package folder and did not create the structure without any error. I am running phpunit 11.4
