### ISSUE TITLE
PHP 8.1 Support

### ISSUE THREAD

**Issue by allejo** [bovigo/vfsStream#263]
Hello and welcome fellow PHP developers preparing for the [8.1 release scheduled for later this year](https://wiki.php.net/todo/php81) :wave:

The current stable release of vfsStream is the 1.6.x series (located in the `v1.6` branch); this series of vfsStream is in maintenance mode only and is only expecting to see small fixes.

## If you're developing for 8.1

If you're a library or project that is developing for PHP 8.1, use our `1.6.10-alpha.*` series of tags and report issues to us. These are marked as "pre-releases" because we don't want to spam releases that have no new features.

When PHP 8.1 has been released, we will tag a stable release of vfsStream supporting PHP 8.1.

## If you don't care about 8.1 yet

If you're not actively developing for PHP 8.1, the latest stable release 1.6.9 will work for you just fine.

**Comment by ADmad** [comment]
`phpspec/prophecy` now has a new release with PHP 8.1 support. So the `--ignore-platform-deps` here can be removed https://github.com/bovigo/vfsStream/blob/953553b0731b45f44750aaa8dc1f69d241f8f657/.github/workflows/runTests.yml#L57

Also with PHP 8.1 RC out it would be nice to have a stable release of `1.6.10` (unless there are other changes planned for this series).

**Comment by alexpott** [comment]
@allejo now we're at PHP 8.1 RC2 is there any chance that 1.6.10 can be released so that your dependencies can make stable releases that are compatible with PHP 8.1 when it is out. I created the MR #268 to address the last work around for your testing dependencies.

**Comment by allejo** [comment]
On it! Let me run some final tests this week and I'll get a tag pushed

**Comment by allejo** [comment]
As promised, [stable v1.6.10 has been published](https://github.com/bovigo/vfsStream/releases/tag/v1.6.10) :tada:
