### ISSUE TITLE
PHP 8.4 Support

### ISSUE THREAD

**Issue by andypost** [bovigo/vfsStream#289]
Attempted to use it with current PHP 8.4 for Drupal 11 core and faced 3 deprecations caused by https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated

https://wiki.php.net/rfc/deprecate-implicitly-nullable-types

**Comment by andypost** [comment]
in[ 2 weeks](https://wiki.php.net/todo/php84) final deprecations will be settled https://wiki.php.net/rfc/deprecations_php_8_4

**Comment by andypost** [comment]
no other deprecations been detected in PHP 8.4 beta3, please create new release

**Comment by andypost** [comment]
Beta3 is out and tests of Drupal core showed no regressions so consider it fixed and awaiting new release to get rid of patch

**Comment by jaapio** [comment]
Tags is created, and should now support php 8.4!

**Comment by andypost** [comment]
Thank you a lot!
