### ISSUE TITLE
`file_put_contents` with exclusive lock set reports error

### ISSUE THREAD

**Issue by iwyg** [bovigo/vfsStream#44]
Writing to a file using `file_put_contents` and `LOCK_EX` set will report an error `Exclusive locks may only be set for regular files` however using `flock($resource, LOCL_EX)` works. 

I've attached a testcase [here](http://dl.dropbox.com/u/17036738/vfsstream_test.tgz)

Thanks.

**Comment by drupalista-br** [comment]
Do you know any workaround for this issue? 
I ran into this when firing parse_ini_file($file_path, TRUE);

**Comment by mikey179** [comment]
Not sure I understand your problem correctly, do you have short code snippet which makes it reproducible?

**Comment by drupalista-br** [comment]
I am sorry, just realized that I copied and pasted the wrong code. I meant to say Zend\Config\Writer\Ini(); instead of parse_ini_file($file_path, TRUE);

Basically when Zend\Config\Writer\Ini(); tries to save into the vfsStream virtual folder, it spits back the fore-mentioned error.

So, are you aware of a workaround for testing it without having to actually save the file into the filesystem?

**Comment by mikey179** [comment]
I don't see a way to work around this in PHP. However, when looking into `Zend\Config\Writer\Ini` I saw that the write mechanism is in `Zend\Config\Writer\AbstractWriter::toFile()` which has a third parameter that allows to disable the exclusive lock. The file would be written without a lock then, maybe that's ok for your use case.

**Comment by drupalista-br** [comment]
Cheers mate, that will do.

**Comment by pondermatic** [comment]
In the PHP ```file_put_contents()``` [code](https://github.com/php/php-src/blob/php-7.2.0/ext/standard/file.c), if the ```LOCK_EX``` flag is set and the filename starts with ```file://```, an ```E_WARNING``` error is returned with the message ```Exclusive locks may only be set for regular files```.

I tried changing ```vfsStream::SCHEME``` from ```vfs``` to ```file``` and calling ```stream_wrapper_unregister('file')``` before ```vfsStreamWrapper::register()``` calls ```stream_wrapper_register()```, but that caused problems with everything else that uses the file system, like autoloaders. There doesn't seem to be a way to fix this issue from inside vfsStream.
