### ISSUE TITLE
PHP Warning with include_path() and stream_resolve_include_path()

### ISSUE THREAD

**Issue by mikey179** [bovigo/vfsStream#5]
From https://code.google.com/p/bovigo/issues/detail?id=24

What steps will reproduce the problem?
To reproduce it, Ive use the interactive console (php -a)

```
php > require 'vfsStream.php';
php > vfsStreamWrapper::register();
php > mkdir('vfs://just/a/path',0777,true);
php > set_include_path('vfs://just/a');
php > $a = stream_resolve_include_path('path/unknownFile.php');
PHP Warning:   No such file or directory in .../vfsStreamWrapper.php on line 658
PHP Stack trace:
PHP   1. {main}() php shell code:0
PHP   2. stream_resolve_include_path() php shell code:1
PHP   3. vfsStreamWrapper->url_stat() .../vfsStreamWrapper.php:0
PHP   4. trigger_error() .../vfsStreamWrapper.php:658
```

What version of the product are you using? On what operating system?
Version 0.8.0 (from SVN) with PHP5.3 on Ubuntu 10.10

Please provide any additional information below.
Maybe this has something to do with #3?

**Comment by larsnystrom** [comment]
I have the same problem where `stream_resolve_include_path()` returns false for `vfs://` urls, even though it works fine to `fopen()` them. Did you file a bug report with PHP core?

**Comment by mikey179** [comment]
No, I didn't, as nobody had an issue with that again. Also, the bug report would have been about the missing flag in the call to the vfsStream method. In your case I suspect there must be something else, as `stream_resolve_include_path()` should work just fine when the file exists, see https://github.com/mikey179/vfsStream/commit/f780403e68211c55a9875bb638b8ac7d2c788355#diff-727ee525c70e3fbdc1c65e385ed866d3R56

**Comment by larsnystrom** [comment]
I'm not sure if it's an edge case, but zendframework/zend-validator uses `stream_resolve_include_path` to check if a file exists, see zendframework/zend-validator#77. `stream_resolve_include_path` will return something `!== false` when the file exists, but that doesn't seem to work with `vfsStream`.

To reproduce:

    $vfs = org\bovigo\vfs\vfsStream::setup('root', null, ['file' => 'content']);
    $file = $vfs->getChild('file');

    // echoes bool(false) but should be the path to the file.
    var_dump(stream_resolve_include_path($file->url()));

Compare that to:

    touch(getcwd() . "/test.tmp");
    // echoes /path/to/test.tmp
    var_dump(stream_resolve_include_path(getcwd() . "/test.tmp"));

**Comment by mikey179** [comment]
In your example you don't add the vfsStream path _vfs://root_ to PHP's _include_path_, whereas the current working directory usually is added to it automatically by PHP. If you add the vfsStream path to the include path as can be seen in the test I linked to it should be resolved correctly.

**Comment by larsnystrom** [comment]
Any absolute path to an existing file is resolved by `stream_resolve_include_path`, not just those in the include path. The problem is that it cannot resolve "absolute" `vfs://` urls. 

For example, the zend validator relies on the fact that any absolute path to an existing file will return something `!== false`. However, when given a `vfs://` "absolute url" `stream_resolve_include_path` returns `false`.

**Comment by mikey179** [comment]
Ah, didn't know about that. Just tested, vfsStream doesn't even get called when an absolute vfsStream path is used with `stream_resolve_include_path`. So there's nothing that it can do about it - but if it would be called it should work out of the box as vfsStream's `url_stat` method would return the correct information.

**Comment by paul-m** [comment]
```
<?php

require_once __DIR__ . '/../vendor/autoload.php';

use org\bovigo\vfs\vfsStream;

$vfs = vfsStream::setup('root');
vfsStream::create(['Hi.php' => '<?php // stuff.'], $vfs);

// checkAndLoad() calls stream_resolve_include_path(). Explosion happens here:
\PHPUnit_Util_Fileloader::checkAndLoad(vfsStream::url('root/Hi.php'));

// [24-Jun-2016 05:38:20 Europe/Berlin] PHP Fatal error:  Uncaught PHPUnit_Framework_Exception:
// Cannot open file "vfs://root/Hi.php".

```
Here's another example. I'm trying to write a PHPUnit test suite loader, and also test the loader. The whole thing is stream safe and can thus be mocked with vfsStream, except for `stream_resolve_include_path()`.

This is where I'm working if you're curious: https://www.drupal.org/node/2499239

**Comment by mikey179** [comment]
As noted above, there is nothing that vfsStream can do about. I added a remark on this in the [list of known issues](https://github.com/mikey179/vfsStream/wiki/Known-Issues). If someone wants to make it work please submit a feature/pull request to PHP core - personally I don't have any deeper interest in that, so I won't take care of that.
